exclude = ["venv*"]
line-length = 99
lint.ignore = [
    "PLR2004",
    "D104",
    "D107",
    "C901",
    "PT023",  # Use `@pytest.mark.asyncio()` over `@pytest.mark.asyncio`
    "PT001",  # Use `@pytest.fixture()` over `@pytest.fixture`
]
lint.select = [
    "C",   # complexity
    "D",   # docstrings
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "PT",  # flake8-pytest
    "RUF", # ruff base config
    "SIM", # flake-simplify
    "W",   # pycodestyle warnings
    "YTT", # flake8-2020
    # "ARG", # flake8-unused args
    # "B"    # bandit
]
[lint.pydocstyle]
convention = "pep257"
